databases:
  - name: apply
    databaseName: apply
    user: apply

services:
  - type: web
    name: apply
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apply
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false